### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by maaatsu** [maaatsu/furima-39302#20]
# 自身のフリマアプリのURL
https://furima-39302.onrender.com/

# Basic認証のIDとパスワード
admin
2222

# 出品者用のメールアドレスとパスワード
メールアドレス：mail@mail
パスワード：asd123

# 購入者用のメールアドレスとパスワード
メールアドレス：mail@mail.mail
パスワード：qwe123

**Comment by shodai-ito** [comment]
@maaatsu さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログアウト状態の場合は、商品購入ページに遷移しようとすると、商品の販売状況に関わらずログインページに遷移すること**
ログアウト状態で購入ページに遷移しようとすると、ログインページに遷移せずにエラー画面になってしまいます。

- [x] **ログイン状態の場合でも、自身が出品していない売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移すること**
売却済み商品でも出品者以外は購入ページに遷移できてしまいます。

- [x] **issueに記載されたURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されること**
Basic認証が導入されていませんでした。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
@maaatsu さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
